/*
  Jensen Decors — product list (40 items).
  Products 1–40 use the Prime Decor–style shape: handle, title, description,
  price_pkr, compare_at_price_pkr, available, vendor, product_type, tags, image — plus
  legacy fields the shop/cart use: id, name, brand, category, subCategory, price,
  shortDescription, detailDoc, compareNote.
  Optional images[] lists every shot for the product gallery (first item must match image).
  Images under jensen-product-images/ are product-focused wall-art shots (not full room sets).
  On Windows, full paths longer than ~260 characters fail under file:// — ids 2 & 5 use short copies in assets/.
*/
var JENSEN_PRODUCTS = [
  {
    id: 1,
    handle: "birds-over-water-5-panel-nature-wall-art",
    title: "Birds Flying Over Water (5 Panel) Nature Wall Art",
    name: "Birds Flying Over Water (5 Panel) Nature Wall Art",
    brand: "Gloster",
    vendor: "Gloster",
    category: "Metal wall art",
    subCategory: "Nature",
    price: 129,
    price_pkr: "35820.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "5 Panel",
    tags: ["5PS1", "allsplitartwork", "gallerycanvas", "nature"],
    image:
      "jensen-product-images/Birds Flying Over Body Of Water (5 Panel) Nature Wall Art/32_fa176b3d-67a8-44c1-b5f4-c6ad35fd1afd_1000x.jpg",
    images: [
      "jensen-product-images/Birds Flying Over Body Of Water (5 Panel) Nature Wall Art/32_fa176b3d-67a8-44c1-b5f4-c6ad35fd1afd_1000x.jpg",
    ],
    shortDescription:
      "Five-panel nature composition — crisp giclée-style print suitable for statement walls. Indoor display.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "5 panels, nature artwork, wall-mount hardware included",
  },
  {
    id: 2,
    handle: "geometric-gold-white-abstract-4-panel-digital-wall-art",
    title: "Geometric Gold & White Abstract Shapes On Black Background (4 Panel) Digital Wall Art",
    name: "Geometric Gold & White Abstract Shapes On Black Background (4 Panel) Digital Wall Art",
    brand: "WallCraft",
    vendor: "WallCraft",
    category: "Metal wall art",
    subCategory: "Geometric",
    price: 89,
    price_pkr: "24742.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "4 Panel",
    tags: ["4PS1", "abstract", "gallerycanvas", "geometric"],
    image: "assets/pilot-id2-geometric-gold-white.webp",
    images: [
      "assets/pilot-id2-geometric-gold-white.webp",
      "assets/pilot-id2-frame.webp",
      "assets/pilot-id2-thick-frame.webp",
    ],
    shortDescription:
      "Bold geometric abstract in gold and white on black — four-panel split layout for modern interiors.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "4 panels, abstract digital art, matte black / gold palette",
  },
  {
    id: 3,
    handle: "all-black-but-gold-abstract-1-panel-wall-art",
    title: "All Black But Gold Abstract Wall Art",
    name: "All Black But Gold Abstract Wall Art",
    brand: "Artisan",
    vendor: "Artisan",
    category: "Metal wall art",
    subCategory: "Abstract",
    price: 159,
    price_pkr: "44202.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "frame", "abstract", "postercollection"],
    image: "jensen-product-images/All Black But Gold/front_4321e1c2-9dee-4459-ac96-a363742c7c9f_1000x.webp",
    images: [
      "jensen-product-images/All Black But Gold/front_4321e1c2-9dee-4459-ac96-a363742c7c9f_1000x.webp",
      "jensen-product-images/All Black But Gold/294_0839d9d7-8ae6-4c30-b88d-904b85c28051_1000x.webp",
      "jensen-product-images/All Black But Gold/rotate_877b01d9-3583-488b-ba1c-c99fe72cb247_1000x.webp",
    ],
    shortDescription:
      "Single-panel abstract with deep black ground and luminous gold accents — gallery-style focal piece.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "1 panel, abstract, gold foil effect on print",
  },
  {
    id: 4,
    handle: "silhouette-tree-half-moon-landscape-poster-wall-art",
    title: "Silhouette Of Tree Under Half Moon Landscape Poster Wall Art",
    name: "Silhouette Of Tree Under Half Moon Landscape Poster Wall Art",
    brand: "Nordic",
    vendor: "Nordic",
    category: "Metal wall art",
    subCategory: "Nature",
    price: 74,
    price_pkr: "20572.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "landscape", "nature", "postercollection"],
    image:
      "jensen-product-images/Silhouette Of Tree under Half Moon  Landscape Poster Wall Art/1SilhouetteOfTreeunderHalfMoon_LandscapePosterWallArt_1000x.webp",
    images: [
      "jensen-product-images/Silhouette Of Tree under Half Moon  Landscape Poster Wall Art/1SilhouetteOfTreeunderHalfMoon_LandscapePosterWallArt_1000x.webp",
      "jensen-product-images/Silhouette Of Tree under Half Moon  Landscape Poster Wall Art/Frame_Border_Colors_f0f35bf6-66c1-4c7c-87af-e7ea14871cde_1000x.webp",
      "jensen-product-images/Silhouette Of Tree under Half Moon  Landscape Poster Wall Art/Thick_Frame_With_Canvas_7a7fd13f-286a-4175-81c2-cecc782f9f90_1000x.webp",
    ],
    shortDescription:
      "Minimal landscape poster — tree silhouette and moon for calm living rooms and bedrooms.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "1 panel, landscape poster, neutral monochrome",
  },
  {
    id: 5,
    handle: "beige-gold-marble-fluid-2-panel-abstract-wall-art",
    title: "Beige & Gold Marble Fluid Design (2 Panel) Abstract Wall Art",
    name: "Beige & Gold Marble Fluid Design (2 Panel) Abstract Wall Art",
    brand: "DecoLine",
    vendor: "DecoLine",
    category: "Wall papers",
    subCategory: "Textured",
    price: 45,
    price_pkr: "12510.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "2 Panel",
    tags: ["240524", "abstract", "texture", "marble"],
    image: "assets/pilot-id5-beige-gold-marble.jpg",
    images: [
      "assets/pilot-id5-beige-gold-marble.jpg",
      "assets/pilot-id5-frame.webp",
      "assets/pilot-id5-thick-frame.webp",
    ],
    shortDescription:
      "Fluid marble in beige and gold across two panels — pairs with warm neutrals and brass accents.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "2 panels, marble abstract, textured fluid design",
  },
  {
    id: 6,
    handle: "flowers-mughal-era-vase-digital-painting-wall-art",
    title: "Flowers In Mughal Era Style Vase Artwork Digital Painting Wall Art",
    name: "Flowers In Mughal Era Style Vase Artwork Digital Painting Wall Art",
    brand: "Gloster",
    vendor: "Gloster",
    category: "Wall papers",
    subCategory: "Floral",
    price: 62,
    price_pkr: "17236.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "floral", "digitalpainting", "postercollection"],
    image:
      "jensen-product-images/Flowers In Mughal Era Style Vase Artwork  Digital Painting Wall Art/648_1000x (1).webp",
    images: [
      "jensen-product-images/Flowers In Mughal Era Style Vase Artwork  Digital Painting Wall Art/648_1000x (1).webp",
      "jensen-product-images/Flowers In Mughal Era Style Vase Artwork  Digital Painting Wall Art/Frame_Border_Colors_70356ee1-8c26-472a-afdb-36e1d2ca480a_1000x.webp",
      "jensen-product-images/Flowers In Mughal Era Style Vase Artwork  Digital Painting Wall Art/Thick_Frame_With_Canvas_414d34ef-0f98-4991-ba84-582ddf580a54_1000x.webp",
    ],
    shortDescription:
      "Mughal-inspired floral vase composition — rich color and fine detail for dining rooms and lounges.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Floral digital painting style, multiple finish options in gallery",
  },
  {
    id: 7,
    handle: "seascape-3-panel-abstract-wall-art",
    title: "Seascape (3 Panel) Abstract Wall Art",
    name: "Seascape (3 Panel) Abstract Wall Art",
    brand: "WallCraft",
    vendor: "WallCraft",
    category: "Wall papers",
    subCategory: "Minimal",
    price: 38,
    price_pkr: "10564.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "3 Panel",
    tags: ["3PS1", "abstract", "minimal", "seascape"],
    image: "jensen-product-images/Seascape (3 Panel) Abstract Wall Art/Seascape_3Panel_AbstractWallArt_1000x.webp",
    images: [
      "jensen-product-images/Seascape (3 Panel) Abstract Wall Art/Seascape_3Panel_AbstractWallArt_1000x.webp",
    ],
    shortDescription:
      "Soft coastal abstract in three panels — minimal palette for calm, airy spaces.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "3 panels, abstract seascape, cool tones",
  },
  {
    id: 8,
    handle: "customized-squared-wall-art-multi-panel",
    title: "Customized Squared Wall Art (Multi Panel)",
    name: "Customized Squared Wall Art (Multi Panel)",
    brand: "FrameHaus",
    vendor: "FrameHaus",
    category: "Photo frame art",
    subCategory: "Gallery",
    price: 95,
    price_pkr: "26410.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "Multi Panel",
    tags: ["gallery", "multipanel", "custom", "square"],
    image:
      "jensen-product-images/Customized Squared Wall Art (Multi Panel)/1_ea489661-c762-44be-85c5-ea2bffe1450f_1000x (1).webp",
    images: [
      "jensen-product-images/Customized Squared Wall Art (Multi Panel)/1_ea489661-c762-44be-85c5-ea2bffe1450f_1000x (1).webp",
      "jensen-product-images/Customized Squared Wall Art (Multi Panel)/2_90eee4f7-e93a-463e-87a0-14e19c72c7ae_1000x (1).webp",
      "jensen-product-images/Customized Squared Wall Art (Multi Panel)/3_f22edd95-f8a2-4dc8-acc0-77e0407e27c5_1000x (1).webp",
      "jensen-product-images/Customized Squared Wall Art (Multi Panel)/Frame_Border_Colors_eb5ccd97-600b-4944-b88f-6e717513977b_1000x.webp",
    ],
    shortDescription:
      "Modular squared layout — mix panels for a gallery wall or symmetrical grid.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Multi-panel squared set, frame border option shown in gallery",
  },
  {
    id: 9,
    handle: "kun-fayakun-abstract-single-panel-islamic-wall-art",
    title: "Kun Fayakun Abstract Background (Single Panel) Islamic Wall Art",
    name: "Kun Fayakun Abstract Background (Single Panel) Islamic Wall Art",
    brand: "Artisan",
    vendor: "Artisan",
    category: "Photo frame art",
    subCategory: "Single",
    price: 48,
    price_pkr: "13344.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "islamic", "calligraphy", "singlepanel"],
    image:
      "jensen-product-images/Kun Fayakun Abstract Background (Single Panel) Islamic Wall Art/KunFayakunAbstractBackground_SinglePanel_IslamicWallArt_1000x.webp",
    images: [
      "jensen-product-images/Kun Fayakun Abstract Background (Single Panel) Islamic Wall Art/KunFayakunAbstractBackground_SinglePanel_IslamicWallArt_1000x.webp",
    ],
    shortDescription:
      "Single-panel abstract Islamic wall art with balanced typography and soft background texture.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "1 panel, Islamic abstract, single focal piece",
  },
  {
    id: 10,
    handle: "world-map-silver-black-currency-3-panel-office-wall-art",
    title: "World Map Silver Black Currency Background (3 Panel) Office Wall Art",
    name: "World Map Silver Black Currency Background (3 Panel) Office Wall Art",
    brand: "DecoLine",
    vendor: "DecoLine",
    category: "Photo frame art",
    subCategory: "Collage",
    price: 72,
    price_pkr: "20016.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "3 Panel",
    tags: ["3PS1", "office", "worldmap", "collage"],
    image:
      "jensen-product-images/World Map Silver Black Currency Background (3 Panel) Office Wall Art/WorldMapSilverBlackCurrencyBackground_3Panel_OfficeWallArt_1000x.jpg",
    images: [
      "jensen-product-images/World Map Silver Black Currency Background (3 Panel) Office Wall Art/WorldMapSilverBlackCurrencyBackground_3Panel_OfficeWallArt_1000x.jpg",
    ],
    shortDescription:
      "Triptych world map with silver–black currency styling — strong for offices and study walls.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "3 panels, map triptych, office styling",
  },
  {
    id: 11,
    handle: "full-moon-red-lilies-3-panel-landscape-wall-art",
    title: "Full Moon Behind the Red Lilies (3 Panel) Landscape Wall Art",
    name: "Full Moon Behind the Red Lilies (3 Panel) Landscape Wall Art",
    brand: "Gloster",
    vendor: "Gloster",
    category: "Mirror art",
    subCategory: "Round",
    price: 210,
    price_pkr: "58380.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "3 Panel",
    tags: ["3PS1", "landscape", "moon", "floral"],
    image:
      "jensen-product-images/Full Moon Behind the Red Lilies (3 Panel) Landscape Wall Art/FullMoonBehindtheRedLilies_3Panel_LandscapeWallArt_1000x.webp",
    images: [
      "jensen-product-images/Full Moon Behind the Red Lilies (3 Panel) Landscape Wall Art/FullMoonBehindtheRedLilies_3Panel_LandscapeWallArt_1000x.webp",
    ],
    shortDescription:
      "Landscape triptych with full moon and red lilies — bold focal art with a round lunar accent.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "3 panels, moon + lilies landscape",
  },
  {
    id: 12,
    handle: "coast-sea-nature-poster-wall-art",
    title: "Coast Sea Nature Poster Wall Art",
    name: "Coast Sea Nature Poster Wall Art",
    brand: "Nordic",
    vendor: "Nordic",
    category: "Mirror art",
    subCategory: "Decorative",
    price: 185,
    price_pkr: "51430.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "nature", "coastal", "poster"],
    image:
      "jensen-product-images/Coast Sea  Nature Poster Wall Art/Colorful-Poster-Vertical_02-Mockup_4ee90c70-7fbc-43b2-af44-39ff447b77f6_1000x.webp",
    images: [
      "jensen-product-images/Coast Sea  Nature Poster Wall Art/Colorful-Poster-Vertical_02-Mockup_4ee90c70-7fbc-43b2-af44-39ff447b77f6_1000x.webp",
      "jensen-product-images/Coast Sea  Nature Poster Wall Art/Frame_Border_Colors_52c09f0d-a9c9-4af6-b327-c80c6d7faae9_1000x.webp",
      "jensen-product-images/Coast Sea  Nature Poster Wall Art/Thick_Frame_With_Canvas_03fa0ba1-3684-4674-9d54-005a9c80343d_1000x.webp",
    ],
    shortDescription:
      "Coastal nature poster — cool blues and horizon line for hallways and bedrooms.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Nature poster, frame and canvas variants in gallery",
  },
  {
    id: 13,
    handle: "law-order-5-panel-lawyer-office-wall-art",
    title: "Law & Order (5 Panel) Lawyer Office Wall Art",
    name: "Law & Order (5 Panel) Lawyer Office Wall Art",
    brand: "WallCraft",
    vendor: "WallCraft",
    category: "Wall shelves",
    subCategory: "Floating",
    price: 68,
    price_pkr: "18904.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "5 Panel",
    tags: ["5PS1", "office", "law", "gallerycanvas"],
    image:
      "jensen-product-images/Law & Order (5 Panel) Lawyer Office Wall Art/Law_Order_5Panel_LawyerOfficeWallArt_1000x.webp",
    images: [
      "jensen-product-images/Law & Order (5 Panel) Lawyer Office Wall Art/Law_Order_5Panel_LawyerOfficeWallArt_1000x.webp",
    ],
    shortDescription:
      "Five-panel office wall set — structured layout suited to professional spaces.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "5 panels, lawyer/office theme",
  },
  {
    id: 14,
    handle: "copper-ocean-blue-3-panel-abstract-wall-art",
    title: "Copper & Ocean Blue (3 Panel) Abstract Wall Art",
    name: "Copper & Ocean Blue (3 Panel) Abstract Wall Art",
    brand: "DecoLine",
    vendor: "DecoLine",
    category: "Wall shelves",
    subCategory: "Corner",
    price: 52,
    price_pkr: "14456.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "3 Panel",
    tags: ["3PS1", "abstract", "copper", "blue"],
    image:
      "jensen-product-images/Copper & Ocean Blue (3 Panel) Abstract Wall Art/Copper_OceanBlue_3Panel_AbstractWallArt_1000x.jpg",
    images: [
      "jensen-product-images/Copper & Ocean Blue (3 Panel) Abstract Wall Art/Copper_OceanBlue_3Panel_AbstractWallArt_1000x.jpg",
    ],
    shortDescription:
      "Fluid copper and ocean blue abstract across three panels — corner-friendly vertical flow.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "3 panels, copper + blue abstract",
  },
  {
    id: 15,
    handle: "motivation-messages-4-panel-office-wall-art",
    title: "Motivation Messages (4 Panel) Office Wall Art",
    name: "Motivation Messages (4 Panel) Office Wall Art",
    brand: "Artisan",
    vendor: "Artisan",
    category: "Wall shelves",
    subCategory: "Modular",
    price: 140,
    price_pkr: "38920.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "4 Panel",
    tags: ["4PS1", "office", "motivation", "typography"],
    image: "jensen-product-images/Motivation Messages (4 Panel) Office Wall Art/1Set2_1000x.webp",
    images: [
      "jensen-product-images/Motivation Messages (4 Panel) Office Wall Art/1Set2_1000x.webp",
      "jensen-product-images/Motivation Messages (4 Panel) Office Wall Art/Frame_Border_Colors_f0f35bf6-66c1-4c7c-87af-e7ea14871cde_1000x.webp",
      "jensen-product-images/Motivation Messages (4 Panel) Office Wall Art/Thick_Frame_With_Canvas_7a7fd13f-286a-4175-81c2-cecc782f9f90_1000x.webp",
    ],
    shortDescription:
      "Four-panel motivational typography set — modular grid for offices and studios.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "4 panels, motivational copy, alternate frames in gallery",
  },
  {
    id: 16,
    handle: "spiritual-dancers-4-5-panel-wall-art",
    title: "Spiritual Dancers #4 (5 Panel) Wall Art",
    name: "Spiritual Dancers #4 (5 Panel) Wall Art",
    brand: "FrameHaus",
    vendor: "FrameHaus",
    category: "Wall shelves",
    subCategory: "Modular",
    price: 88,
    price_pkr: "24464.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "5 Panel",
    tags: ["5PS1", "dance", "spiritual", "gallerycanvas"],
    image:
      "jensen-product-images/Spiritual Dancers #4 (5 Panel) Wall Art/SpiritualDancers_4_5Panel_WallArt_1000x.webp",
    images: [
      "jensen-product-images/Spiritual Dancers #4 (5 Panel) Wall Art/SpiritualDancers_4_5Panel_WallArt_1000x.webp",
    ],
    shortDescription:
      "Five-panel spiritual dancers composition — rhythm and movement for feature walls.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "5 panels, spiritual dancers artwork",
  },
  {
    id: 17,
    handle: "attitude-lion-animal-poster-wall-art",
    title: "Attitude Lion Animal Poster Wall Art",
    name: "Attitude Lion Animal Poster Wall Art",
    brand: "Gloster",
    vendor: "Gloster",
    category: "Wall mounted animals",
    subCategory: "Safari",
    price: 199,
    price_pkr: "55322.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "lion", "safari", "animal"],
    image:
      "jensen-product-images/Attitude Lion Animal Poster Wall Art/AttitudeLionAnimalPosterWallArt_3f579e70-c7a1-4b5b-90c8-a2b205d0b84f_1000x.jpg",
    images: [
      "jensen-product-images/Attitude Lion Animal Poster Wall Art/AttitudeLionAnimalPosterWallArt_3f579e70-c7a1-4b5b-90c8-a2b205d0b84f_1000x.jpg",
      "jensen-product-images/Attitude Lion Animal Poster Wall Art/Frame_Border_Colors_cad6b2d1-0cbb-4755-8d62-d21c5c140dc6_1000x.webp",
      "jensen-product-images/Attitude Lion Animal Poster Wall Art/Thick_Frame_With_Canvas_e8182bf4-b657-403f-9711-4faeda2fece0_1000x.webp",
    ],
    shortDescription:
      "Bold lion portrait poster — high-contrast animal art for living rooms and offices.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "1 panel, lion poster, frame options in gallery",
  },
  {
    id: 18,
    handle: "see-the-beauty-nature-poster-wall-art",
    title: "See the Beauty | Nature Poster Wall Art",
    name: "See the Beauty | Nature Poster Wall Art",
    brand: "Nordic",
    vendor: "Nordic",
    category: "Wall mounted animals",
    subCategory: "Birds",
    price: 56,
    price_pkr: "15568.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "nature", "birds", "poster"],
    image:
      "jensen-product-images/See the Beauty  Nature Poster Wall Art/Colorful-Poster-Vertical_02-Mockup_e9cd0f93-f3dc-4fac-92b7-d6cc71df9257_1000x.webp",
    images: [
      "jensen-product-images/See the Beauty  Nature Poster Wall Art/Colorful-Poster-Vertical_02-Mockup_e9cd0f93-f3dc-4fac-92b7-d6cc71df9257_1000x.webp",
      "jensen-product-images/See the Beauty  Nature Poster Wall Art/Frame_Border_Colors_f4c1d9a8-bde8-4e03-9642-c7886fe6bd89_1000x.webp",
      "jensen-product-images/See the Beauty  Nature Poster Wall Art/Thick_Frame_With_Canvas_aaf97b68-0678-474c-92c2-3d0a03e44bda_1000x.webp",
    ],
    shortDescription:
      "Nature poster with soft color — uplifting wall art for bedrooms and reading nooks.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Nature poster, vertical mockup + frame variants",
  },
  {
    id: 19,
    handle: "running-horse-animal-poster-wall-art",
    title: "Running Horse Animal Poster Wall Art",
    name: "Running Horse Animal Poster Wall Art",
    brand: "WallCraft",
    vendor: "WallCraft",
    category: "Wall mounted animals",
    subCategory: "Farm",
    price: 42,
    price_pkr: "11676.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "horse", "farm", "animal"],
    image:
      "jensen-product-images/Running Horse  Animal Poster Wall Art/Colorful-Poster-Vertical_02-Mockup_fb12f4fb-fbd2-4c9d-988b-8a5867f5ccba_1000x.webp",
    images: [
      "jensen-product-images/Running Horse  Animal Poster Wall Art/Colorful-Poster-Vertical_02-Mockup_fb12f4fb-fbd2-4c9d-988b-8a5867f5ccba_1000x.webp",
    ],
    shortDescription:
      "Dynamic running horse poster — vertical layout for narrow walls and entryways.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "1 panel, horse animal poster",
  },
  {
    id: 20,
    handle: "elegant-horses-running-in-wind-4-panel-animal-wall-art",
    title: "Elegant Horses Running in Wind (4 Panel) Animal Wall Art",
    name: "Elegant Horses Running in Wind (4 Panel) Animal Wall Art",
    brand: "Artisan",
    vendor: "Artisan",
    category: "Wall mounted animals",
    subCategory: "Safari",
    price: 78,
    price_pkr: "21684.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "4 Panel",
    tags: ["4PS1", "horse", "animal", "landscape"],
    image:
      "jensen-product-images/Elegant Horses Running in Wind (4 Panel) Animal Wall Art/ElegantHorsesRunninginWind_4Panel_AnimalWallArt_1000x.jpg",
    images: [
      "jensen-product-images/Elegant Horses Running in Wind (4 Panel) Animal Wall Art/ElegantHorsesRunninginWind_4Panel_AnimalWallArt_1000x.jpg",
    ],
    shortDescription:
      "Four-panel galloping horses — movement and warmth for wide walls.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "4 panels, horses animal wall art",
  },
  {
    id: 21,
    handle: "arabic-calligraphy-art-5-panel-islamic-wall-art",
    title: "Arabic Calligraphy Art (5 Panel) Islamic Wall Art",
    name: "Arabic Calligraphy Art (5 Panel) Islamic Wall Art",
    brand: "Gloster",
    vendor: "Gloster",
    category: "Metal wall art",
    subCategory: "Nature",
    price: 92,
    price_pkr: "25576.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "5 Panel",
    tags: ["5PS1", "islamic", "calligraphy", "gallerycanvas"],
    image:
      "jensen-product-images/Arabic Calligraphy Art (5 Panel) Islamic Wall Art/7_c9ef6d03-9478-42c4-a2d1-7c8a76bdf07b_1000x.webp",
    images: [
      "jensen-product-images/Arabic Calligraphy Art (5 Panel) Islamic Wall Art/7_c9ef6d03-9478-42c4-a2d1-7c8a76bdf07b_1000x.webp",
    ],
    shortDescription:
      "Five-panel Arabic calligraphy — refined Islamic wall art for formal spaces.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "5 panels, Islamic calligraphy",
  },
  {
    id: 22,
    handle: "darwesh-sufi-dancers-2-panel-digital-wall-art",
    title: "Darwesh Sufi Dancers Oil Paint Art (2 Panel) Digital Wall Art",
    name: "Darwesh Sufi Dancers Oil Paint Art (2 Panel) Digital Wall Art",
    brand: "WallCraft",
    vendor: "WallCraft",
    category: "Metal wall art",
    subCategory: "Geometric",
    price: 85,
    price_pkr: "23630.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "2 Panel",
    tags: ["240524", "sufi", "digital", "oilpaint"],
    image:
      "jensen-product-images/Darwesh Sufi Dancers Oil Paint Art (2 Panel) Digital Wall Art/1DarweshSufiDancersOilPaintArt_2Panel_DigitalWallArt_1000x.jpg",
    images: [
      "jensen-product-images/Darwesh Sufi Dancers Oil Paint Art (2 Panel) Digital Wall Art/1DarweshSufiDancersOilPaintArt_2Panel_DigitalWallArt_1000x.jpg",
      "jensen-product-images/Darwesh Sufi Dancers Oil Paint Art (2 Panel) Digital Wall Art/Frame_Border_Colors_676785c7-a7a5-43e4-a08a-376d41a8cc6c_1000x.webp",
      "jensen-product-images/Darwesh Sufi Dancers Oil Paint Art (2 Panel) Digital Wall Art/Thick_Frame_With_Canvas_0691b723-787b-413b-9bf8-f4adfd54fdb8_1000x.webp",
    ],
    shortDescription:
      "Two-panel Sufi dancers in oil-paint style — cultural art with rich color.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "2 panels, Sufi dancers digital art",
  },
  {
    id: 23,
    handle: "dusty-transparent-sabr-shukr-tawakul-3-panel-islamic-wall-art",
    title: "Dusty Transparent Sabr, Shukr, Tawakul (3 Panel) Islamic Wall Art",
    name: "Dusty Transparent Sabr, Shukr, Tawakul (3 Panel) Islamic Wall Art",
    brand: "Artisan",
    vendor: "Artisan",
    category: "Metal wall art",
    subCategory: "Abstract",
    price: 110,
    price_pkr: "30580.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "3 Panel",
    tags: ["3PS1", "islamic", "typography", "minimal"],
    image:
      "jensen-product-images/Dusty Transparent Sabr, Shukr, Tawakul (3 Panel) Islamic Wall Art/dustytransparentsabrshukrtawakul_86197c1b-8ca1-4e33-813d-e3d0e1d21c2a_1000x.webp",
    images: [
      "jensen-product-images/Dusty Transparent Sabr, Shukr, Tawakul (3 Panel) Islamic Wall Art/dustytransparentsabrshukrtawakul_86197c1b-8ca1-4e33-813d-e3d0e1d21c2a_1000x.webp",
      "jensen-product-images/Dusty Transparent Sabr, Shukr, Tawakul (3 Panel) Islamic Wall Art/Frame_Border_Colors_9d41fcf8-6cad-413c-9f0c-29bf549c5d3b_1000x.webp",
      "jensen-product-images/Dusty Transparent Sabr, Shukr, Tawakul (3 Panel) Islamic Wall Art/Thick_Frame_With_Canvas_1a3d7952-ac35-4bf3-9d30-9066d9b15ea1_1000x.webp",
    ],
    shortDescription:
      "Three-panel Sabr, Shukr, Tawakul — soft dusty tones for calm interiors.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "3 panels, Islamic typography triptych",
  },
  {
    id: 24,
    handle: "ayatul-kursi-black-gold-5-panel-islamic-wall-art",
    title: "Ayatul Kursi Black & Gold Textured Background (5 Panel) Islamic Wall Art",
    name: "Ayatul Kursi Black & Gold Textured Background (5 Panel) Islamic Wall Art",
    brand: "Nordic",
    vendor: "Nordic",
    category: "Wall papers",
    subCategory: "Textured",
    price: 125,
    price_pkr: "34750.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "5 Panel",
    tags: ["5PS1", "islamic", "ayatulkursi", "gold"],
    image:
      "jensen-product-images/Ayatul Kursi Balck & Gold Textured Background (5 Panel) Islamic Wall Art/155_c552b3c5-883c-47a8-a924-75d55c5ae315_1000x.jpg",
    images: [
      "jensen-product-images/Ayatul Kursi Balck & Gold Textured Background (5 Panel) Islamic Wall Art/155_c552b3c5-883c-47a8-a924-75d55c5ae315_1000x.jpg",
    ],
    shortDescription:
      "Ayatul Kursi on black and gold texture — five-panel statement Islamic wall art.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "5 panels, black & gold Islamic calligraphy",
  },
  {
    id: 25,
    handle: "spiritual-dancers-7-3-panel-wall-art",
    title: "Spiritual Dancers #7 (3 Panel) Wall Art",
    name: "Spiritual Dancers #7 (3 Panel) Wall Art",
    brand: "DecoLine",
    vendor: "DecoLine",
    category: "Wall papers",
    subCategory: "Minimal",
    price: 115,
    price_pkr: "31970.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "3 Panel",
    tags: ["3PS1", "dance", "spiritual", "minimal"],
    image:
      "jensen-product-images/Spiritual Dancers #7 (3 Panel) Wall Art/SpiritualDancers_7_3Panel_WallArt_1000x.webp",
    images: [
      "jensen-product-images/Spiritual Dancers #7 (3 Panel) Wall Art/SpiritualDancers_7_3Panel_WallArt_1000x.webp",
    ],
    shortDescription:
      "Three-panel spiritual dancers — balanced layout for modern minimal rooms.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "3 panels, spiritual dancers series",
  },
  {
    id: 26,
    handle: "hasbunallah-wanimal-wakil-5-panel-islamic-wall-art",
    title: "Hasbunallah wanimal wakil #2 (5 Panel) Islamic Wall Art",
    name: "Hasbunallah wanimal wakil #2 (5 Panel) Islamic Wall Art",
    brand: "FrameHaus",
    vendor: "FrameHaus",
    category: "Photo frame art",
    subCategory: "Gallery",
    price: 98,
    price_pkr: "27244.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "5 Panel",
    tags: ["5PS1", "islamic", "calligraphy", "gallerycanvas"],
    image:
      "jensen-product-images/Hasbunallah wanimal wakil #2 (5 Panel) Islamic Wall Art/20_1000x.webp",
    images: [
      "jensen-product-images/Hasbunallah wanimal wakil #2 (5 Panel) Islamic Wall Art/20_1000x.webp",
    ],
    shortDescription:
      "Five-panel Hasbunallah composition — bold Islamic typography for wide walls.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "5 panels, Hasbunallah Islamic wall art",
  },
  {
    id: 27,
    handle: "bmw-m5-car-poster-wall-art",
    title: "BMW M5 Car Poster Wall Art",
    name: "BMW M5 Car Poster Wall Art",
    brand: "Gloster",
    vendor: "Gloster",
    category: "Photo frame art",
    subCategory: "Single",
    price: 175,
    price_pkr: "48650.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "cars", "bmw", "poster"],
    image:
      "jensen-product-images/BMW M5  Car Poster Wall Art/Colorful-Poster-Vertical_02-Mockup_df208cff-34bf-4efe-9a04-a6fdc7f0ca49_1000x.webp",
    images: [
      "jensen-product-images/BMW M5  Car Poster Wall Art/Colorful-Poster-Vertical_02-Mockup_df208cff-34bf-4efe-9a04-a6fdc7f0ca49_1000x.webp",
      "jensen-product-images/BMW M5  Car Poster Wall Art/Frame_Border_Colors_93ba34b3-0d2c-4b62-bb3f-d40f3613beea_1000x.webp",
      "jensen-product-images/BMW M5  Car Poster Wall Art/Thick_Frame_With_Canvas_47f9c39a-58d6-455a-8f27-47b9014c5f0d_1000x.webp",
    ],
    shortDescription:
      "BMW M5 automotive poster — vertical layout with optional frame finishes.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Car poster, mockup + frame variants",
  },
  {
    id: 28,
    handle: "toyota-supra-orange-car-wall-art",
    title: "Toyota Supra Orange Background Cars Wall Art",
    name: "Toyota Supra Orange Background Cars Wall Art",
    brand: "WallCraft",
    vendor: "WallCraft",
    category: "Photo frame art",
    subCategory: "Collage",
    price: 165,
    price_pkr: "45870.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "cars", "toyota", "sports"],
    image: "jensen-product-images/Toyota Supra Orange/Toyota_940x (1).webp",
    images: ["jensen-product-images/Toyota Supra Orange/Toyota_940x (1).webp"],
    shortDescription:
      "Toyota Supra on orange — high-energy car art for garages and game rooms.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "1 panel, Toyota Supra automotive art",
  },
  {
    id: 29,
    handle: "nissan-gtr-generations-5-panel-cars-wall-art",
    title: "Nissan GTR Generations (5 Panel) Cars Wall Art",
    name: "Nissan GTR Generations (5 Panel) Cars Wall Art",
    brand: "Artisan",
    vendor: "Artisan",
    category: "Mirror art",
    subCategory: "Round",
    price: 180,
    price_pkr: "50040.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "5 Panel",
    tags: ["5PS1", "cars", "nissan", "gtr"],
    image:
      "jensen-product-images/Nissan GTR Generations (5 Panel) Cars Wall Art/NissanGTRGenerations_5Panel_CarsWallArt_1000x.jpg",
    images: [
      "jensen-product-images/Nissan GTR Generations (5 Panel) Cars Wall Art/NissanGTRGenerations_5Panel_CarsWallArt_1000x.jpg",
    ],
    shortDescription:
      "Five-panel Nissan GTR generations — automotive heritage wall display.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "5 panels, Nissan GTR lineup art",
  },
  {
    id: 30,
    handle: "neon-car-5-panel-movie-wall-art",
    title: "Neon Car (5 Panel) Movie Wall Art",
    name: "Neon Car (5 Panel) Movie Wall Art",
    brand: "Nordic",
    vendor: "Nordic",
    category: "Mirror art",
    subCategory: "Decorative",
    price: 155,
    price_pkr: "43090.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "5 Panel",
    tags: ["5PS1", "neon", "movie", "cars"],
    image:
      "jensen-product-images/Neon Car (5 Panel) Movie Wall Art/NeonCar_5Panel_MovieWallArt_1000x.webp",
    images: [
      "jensen-product-images/Neon Car (5 Panel) Movie Wall Art/NeonCar_5Panel_MovieWallArt_1000x.webp",
    ],
    shortDescription:
      "Neon-lit car movie-style five-panel set — cinematic color for feature walls.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "5 panels, neon car movie theme",
  },
  {
    id: 31,
    handle: "nissan-gtr-80s-style-cars-poster-wall-art",
    title: "Nissan GTR 80's Style Art Cars Poster Wall Art",
    name: "Nissan GTR 80's Style Art Cars Poster Wall Art",
    brand: "DecoLine",
    vendor: "DecoLine",
    category: "Wall shelves",
    subCategory: "Floating",
    price: 170,
    price_pkr: "47260.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "cars", "nissan", "retro"],
    image:
      "jensen-product-images/Nissan GTR 80.s Style Art Cars Poster Wall Art/1NissanGTR80_sStyleArt_CarsPosterWallArt_1000x.webp",
    images: [
      "jensen-product-images/Nissan GTR 80.s Style Art Cars Poster Wall Art/1NissanGTR80_sStyleArt_CarsPosterWallArt_1000x.webp",
      "jensen-product-images/Nissan GTR 80.s Style Art Cars Poster Wall Art/Frame_Border_Colors_e7d3ac92-5714-4505-91ef-2a3da5584bcf_1000x.webp",
      "jensen-product-images/Nissan GTR 80.s Style Art Cars Poster Wall Art/Thick_Frame_With_Canvas_2f91186f-e54e-4b80-ab95-cb7c26deaf73_1000x.webp",
    ],
    shortDescription:
      "Retro Nissan GTR poster — 80s styling with optional frame treatments.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Nissan GTR retro car poster, gallery variants",
  },
  {
    id: 32,
    handle: "netflix-narcos-cash-bullet-movies-poster-wall-art",
    title: "Netflix Narcos Cash & Bullet Movies Poster Wall Art",
    name: "Netflix Narcos Cash & Bullet Movies Poster Wall Art",
    brand: "FrameHaus",
    vendor: "FrameHaus",
    category: "Wall shelves",
    subCategory: "Corner",
    price: 135,
    price_pkr: "37530.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "movie", "poster", "narcos"],
    image:
      "jensen-product-images/Netflix Narcos Cash & Bullet  Movies Poster Wall Art/1NetflixNarcosCash_Bullet_MoviesPosterWallArt_1000x.webp",
    images: [
      "jensen-product-images/Netflix Narcos Cash & Bullet  Movies Poster Wall Art/1NetflixNarcosCash_Bullet_MoviesPosterWallArt_1000x.webp",
      "jensen-product-images/Netflix Narcos Cash & Bullet  Movies Poster Wall Art/Frame_Border_Colors_e3b5b298-bbcd-4e08-88a7-62e31d7573bd_1000x.webp",
      "jensen-product-images/Netflix Narcos Cash & Bullet  Movies Poster Wall Art/Thick_Frame_With_Canvas_738ea738-0939-4c82-86cd-8230750fbc85_1000x.webp",
    ],
    shortDescription:
      "Cinematic Narcos-style poster — cash & bullet motif for media rooms.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Movie poster, frame options in gallery",
  },
  {
    id: 33,
    handle: "thomas-shelby-peaky-blinders-movie-poster-wall-art",
    title: "Thomas Shelby Peaky Blinders Movie Poster Wall Art",
    name: "Thomas Shelby Peaky Blinders Movie Poster Wall Art",
    brand: "Gloster",
    vendor: "Gloster",
    category: "Wall shelves",
    subCategory: "Modular",
    price: 195,
    price_pkr: "54210.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "movie", "peakyblinders", "portrait"],
    image:
      "jensen-product-images/Thomas Shelby Peaky Blinders  Movie Poster Wall Art/1ThomasShelbyPeakyBlinders_MoviePosterWallArt_1000x.webp",
    images: [
      "jensen-product-images/Thomas Shelby Peaky Blinders  Movie Poster Wall Art/1ThomasShelbyPeakyBlinders_MoviePosterWallArt_1000x.webp",
      "jensen-product-images/Thomas Shelby Peaky Blinders  Movie Poster Wall Art/Frame_Border_Colors_bad58787-953d-41ab-a901-db19bd423606_1000x.webp",
      "jensen-product-images/Thomas Shelby Peaky Blinders  Movie Poster Wall Art/Thick_Frame_With_Canvas_8809edf7-3714-44d6-834f-039db180dae4_1000x.webp",
    ],
    shortDescription:
      "Thomas Shelby portrait poster — dramatic character art for fans of the series.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Peaky Blinders poster, multiple frame styles",
  },
  {
    id: 34,
    handle: "quaid-e-azam-muhammad-ali-jinnah-portrait-poster-wall-art",
    title: "Quaid-e-Azam Muhammad Ali Jinnah Portrait | Figure Poster Wall Art",
    name: "Quaid-e-Azam Muhammad Ali Jinnah Portrait | Figure Poster Wall Art",
    brand: "WallCraft",
    vendor: "WallCraft",
    category: "Photo frame art",
    subCategory: "Single",
    price: 145,
    price_pkr: "40310.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "portrait", "figure", "poster"],
    image:
      "jensen-product-images/Quaid-e-Azam Muhammad Ali Jinnah Portrait  Figure Poster Wall Art/Quaid-e-AzamMuhammadAliJinnahPortrait_FigurePosterWallArt_940x.webp",
    images: [
      "jensen-product-images/Quaid-e-Azam Muhammad Ali Jinnah Portrait  Figure Poster Wall Art/Quaid-e-AzamMuhammadAliJinnahPortrait_FigurePosterWallArt_940x.webp",
      "jensen-product-images/Quaid-e-Azam Muhammad Ali Jinnah Portrait  Figure Poster Wall Art/Frame_Border_Colors_cad6b2d1-0cbb-4755-8d62-d21c5c140dc6_1000x.webp",
      "jensen-product-images/Quaid-e-Azam Muhammad Ali Jinnah Portrait  Figure Poster Wall Art/Thick_Frame_With_Canvas_e8182bf4-b657-403f-9711-4faeda2fece0_1000x.webp",
    ],
    shortDescription:
      "Formal portrait figure poster — dignified wall art for offices and libraries.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Figure portrait poster, framing options",
  },
  {
    id: 35,
    handle: "lewis-hamilton-formula-1-sports-wall-art",
    title: "Lewis Hamilton Formula 1 Sports Wall Art",
    name: "Lewis Hamilton Formula 1 Sports Wall Art",
    brand: "Artisan",
    vendor: "Artisan",
    category: "Photo frame art",
    subCategory: "Gallery",
    price: 220,
    price_pkr: "61160.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "f1", "sports", "lewishamilton"],
    image:
      "jensen-product-images/Lewis Hamilton Formula 1  Sports Wall Art/LewisHamiltonFormula1_SportsWallArt_1000x.webp",
    images: [
      "jensen-product-images/Lewis Hamilton Formula 1  Sports Wall Art/LewisHamiltonFormula1_SportsWallArt_1000x.webp",
      "jensen-product-images/Lewis Hamilton Formula 1  Sports Wall Art/Frame_Border_Colors_4c27558c-62b8-4e1e-8412-b714267f8036_1000x.webp",
      "jensen-product-images/Lewis Hamilton Formula 1  Sports Wall Art/Thick_Frame_With_Canvas_0c660a8f-5f49-4736-a501-100ab922375a_1000x.webp",
    ],
    shortDescription:
      "Lewis Hamilton F1 sports poster — speed and precision for motorsport fans.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "F1 sports wall art, Lewis Hamilton",
  },
  {
    id: 36,
    handle: "customise-your-wallpaper",
    title: "Customise Your Wallpaper",
    name: "Customise Your Wallpaper",
    brand: "Nordic",
    vendor: "Nordic",
    category: "Wall papers",
    subCategory: "Textured",
    price: 23,
    price_pkr: "6250.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "Wallpaper Murals",
    tags: ["Custom Wall Mural", "Custom Wallpapers", "officexmural", "Wallpaper", "WPM"],
    image: "jensen-product-images/Customise Your Wallpaper/customwallpaper_1000x.webp",
    images: [
      "jensen-product-images/Customise Your Wallpaper/customwallpaper_1000x.webp",
      "jensen-product-images/Customise Your Wallpaper/Lamination_3d3e9b1c-3cf4-4b84-b488-dfc565dc8ef4_1000x.webp",
      "https://cdn.shopify.com/s/files/1/0653/4735/4872/files/customwallpaper.jpg?v=1752140789",
    ],
    shortDescription:
      "Custom wallpaper murals sized to your wall — self-adhesive, water-proof, with optional lamination.",
    description:
      "Our wallpaper murals are custom made to your exact wall dimensions and are split into the minimum number of panels possible to minimize the number of joins.\nWall Mural Properties:\n\nSelf-Adhesive.\nWater-Proof.\nLamination for extra protection.\nResistant to UV Lights.\nFull color and vibrant inks.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Wallpaper murals — custom dimensions; see Prime catalog image for reference",
  },
  {
    id: 37,
    handle: "7-habits-for-success-motivation-wall-art",
    title: "7 Habits for Success Motivation Wall Art",
    name: "7 Habits for Success Motivation Wall Art",
    brand: "DecoLine",
    vendor: "DecoLine",
    category: "Wall papers",
    subCategory: "Minimal",
    price: 55,
    price_pkr: "15290.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "motivation", "success", "typography"],
    image:
      "jensen-product-images/7 Habits for Success  Motivation Wall Art/7HabitsforSuccessMotivationWallArt_c31d5da2-3c5b-472c-bca7-3b2fe148c064_1000x.jpg",
    images: [
      "jensen-product-images/7 Habits for Success  Motivation Wall Art/7HabitsforSuccessMotivationWallArt_c31d5da2-3c5b-472c-bca7-3b2fe148c064_1000x.jpg",
      "jensen-product-images/7 Habits for Success  Motivation Wall Art/Frame_Border_Colors_77a83486-daa6-44a2-be70-4bf9af1d94db_1000x (1).webp",
      "jensen-product-images/7 Habits for Success  Motivation Wall Art/Thick_Frame_With_Canvas_dee6e88f-4f2c-43d3-b3c1-83dd833419ec_1000x.webp",
    ],
    shortDescription:
      "Seven habits success motivation print — daily inspiration for desks and studios.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Motivation typography, frame variants",
  },
  {
    id: 38,
    handle: "think-positively-network-well-motivational-poster-wall-art",
    title: "Think Positively Network Well Motivational Poster Wall Art",
    name: "Think Positively Network Well Motivational Poster Wall Art",
    brand: "FrameHaus",
    vendor: "FrameHaus",
    category: "Metal wall art",
    subCategory: "Nature",
    price: 58,
    price_pkr: "16124.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "motivation", "office", "networking"],
    image:
      "jensen-product-images/Think Positively Network Well  Motivational Poster Wall Art/ThinkPositivelyNetworkWell_MotivationalPosterWallArt_1000x.webp",
    images: [
      "jensen-product-images/Think Positively Network Well  Motivational Poster Wall Art/ThinkPositivelyNetworkWell_MotivationalPosterWallArt_1000x.webp",
      "jensen-product-images/Think Positively Network Well  Motivational Poster Wall Art/Thick_Frame_With_Canvas_befb2b60-b32d-4cbd-8f28-c81205966b02_1000x.webp",
    ],
    shortDescription:
      "Think positively / network well — motivational copy for coworking and home offices.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Motivational poster, thick frame variant",
  },
  {
    id: 39,
    handle: "think-outside-the-box-motivational-poster-wall-art",
    title: "Think Outside The Box Motivational Poster Wall Art",
    name: "Think Outside The Box Motivational Poster Wall Art",
    brand: "Gloster",
    vendor: "Gloster",
    category: "Metal wall art",
    subCategory: "Geometric",
    price: 60,
    price_pkr: "16680.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "motivation", "creative", "office"],
    image:
      "jensen-product-images/Think Outside The Box Motivational Poster Wall Art/1ThinkOutsidetheBox_MotivationalPosterWallArt_1000x.webp",
    images: [
      "jensen-product-images/Think Outside The Box Motivational Poster Wall Art/1ThinkOutsidetheBox_MotivationalPosterWallArt_1000x.webp",
      "jensen-product-images/Think Outside The Box Motivational Poster Wall Art/Frame_Border_Colors_47784de8-0dd9-4584-bf4d-f339bf9d35d8_1000x.webp",
      "jensen-product-images/Think Outside The Box Motivational Poster Wall Art/Thick_Frame_With_Canvas_f1fe2d8b-0329-4441-94bb-f587bffd1845_1000x.webp",
    ],
    shortDescription:
      "Think outside the box — crisp motivational art for brainstorm zones.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Motivation poster, frame + canvas options",
  },
  {
    id: 40,
    handle: "tiger-portrait-animal-poster-wall-art",
    title: "Tiger Portrait Animal Poster Wall Art",
    name: "Tiger Portrait Animal Poster Wall Art",
    brand: "WallCraft",
    vendor: "WallCraft",
    category: "Metal wall art",
    subCategory: "Abstract",
    price: 188,
    price_pkr: "52264.00",
    compare_at_price_pkr: null,
    available: true,
    product_type: "1 Panel",
    tags: ["0107", "tiger", "animal", "portrait"],
    image:
      "jensen-product-images/Tiger Portrait  Animal Poster Wall Art/Colorful-Poster-Vertical_02-Mockup_f69313e2-3ec4-495c-9002-5bd474d7c74a_1000x.webp",
    images: [
      "jensen-product-images/Tiger Portrait  Animal Poster Wall Art/Colorful-Poster-Vertical_02-Mockup_f69313e2-3ec4-495c-9002-5bd474d7c74a_1000x.webp",
      "jensen-product-images/Tiger Portrait  Animal Poster Wall Art/Frame_Border_Colors_f4c1d9a8-bde8-4e03-9642-c7886fe6bd89_1000x.webp",
      "jensen-product-images/Tiger Portrait  Animal Poster Wall Art/Thick_Frame_With_Canvas_aaf97b68-0678-474c-92c2-3d0a03e44bda_1000x.webp",
    ],
    shortDescription:
      "Tiger portrait poster — intense wildlife focal art for lounges and studios.",
    description:
      "Canvas with Wooden Base:\n\nPrinted on premium quality cotton-canvas.\n1-inch thick wooden back frame.\nNo additional hanging hardware is required.\nCare: Dust with a soft, dry cloth.\n\nFramed With Borders & Acrylic Glass:\n\nPrinted on high grade photo paper.\nPVC borders are used for framing.\n2mm thick acrylic glass is used on top for protection.\nHooks are attached to the back of each frame for hanging.\n\nNote: There may be a slight difference in actual color, due to the colors of display.",
    detailDoc: "docs/products-detail.txt",
    compareNote: "Tiger animal poster, vertical mockup + frames",
  }
];
